---
- name: Create User grafana
  user:
    name: grafana
    create_home: no
    shell: /bin/false
  
- name: Create directories for Grafana
  file:
    path: "/tmp/grafana"
    state: directory

- name: Download Grafana
  copy:
    src: "/etc/ansible/roles/grafana/static/grafana_10.0.2_amd64.deb"
    dest: /tmp/grafana


- name: Install Grafana
  apt:
    deb: "/tmp/grafana/grafana_10.0.2_amd64.deb"

- name: Copy template
  copy:
    src: "/etc/ansible/roles/grafana/templates/main.yml"
    dest: /etc/grafana/provisioning/datasources

- name: Create directories for Dashboards
  file:
    path: "/var/lib/grafana/dashboards"
    state: directory

- name: Copy json
  copy:
    src: "/etc/ansible/roles/grafana/templates/metrics.json"
    dest: /var/lib/grafana/dashboards
    owner: grafana
    group: grafana
